### ISSUE TITLE
Complex objects are not properly displayed in attributes

### ISSUE THREAD

**Issue by ostrovskyde** [hawtio/hawtio-integration#105]
Complex objects values are not disclosed in attributes section.
In case the object (map) encapsulates other objects their values are not displayed. The "object Object" is printed instead. 

See below:
![Hawtio complex attribute view](https://user-images.githubusercontent.com/72016014/94457237-f45ac180-01bc-11eb-9f3b-cbed7f33e7a9.png)

Expected output should be the same as how it is displayed in operations section:

![Hawtio operation result on complex object](https://user-images.githubusercontent.com/72016014/94457494-4dc2f080-01bd-11eb-9928-2cfbf454012b.png)

**Comment by tadayosi** [comment]
It's something we've been thinking of implementing but haven't done yet: hawtio/hawtio#1099

**Comment by ostrovskyde** [comment]
> It's something we've been thinking of implementing but haven't done yet: [hawtio/hawtio#1099](https://github.com/hawtio/hawtio/issues/1099)

Hi Tadayoshi,
Any idea when this could be implemented? Looks like a bug

**Comment by abkieling** [comment]
Just a heads up. The Attributes table is very tricky to change due to the code being shared across different pages. I've tried to refactor it in the past and gave up. If anyone decides to change it, be sure it's a much larger job than it looks.
