### ISSUE TITLE
ThreadDump for all threads

### ISSUE THREAD

**Issue by scarni-trig** [hawtio/hawtio-integration#142]
Hi all,

is it possible to create aggregated thread dump of all JVM threads? I'would expect it to be somewhere in Runtime -> threads tab.

Thanks in advance,

 Simon

**Comment by prahaladhchandrahasan** [comment]
Closed by mistake

**Comment by prahaladhchandrahasan** [comment]
With this final Pull Request: https://github.com/hawtio/hawtio-integration/pull/146. This issue can now be closed
