### ISSUE TITLE
Camel Route diagram enhancements

### ISSUE THREAD

**Issue by trfulcher** [hawtio/hawtio-integration#154]
This is less an issue, more an enhancement request.
I'm using the Camel route diagram feature which is pretty neat, but I have two requests - just curious on their feasibility

1. I've got a bunch of routes which all inherit from the same RouteBuilder that defines a common Exception Handler. When the diagrams render of course the value is slightly buried since the exception handle path is repeated each time (often the steps are more than the underlying route itself). Any chance there could be an option to either suppress rendering this, or some how render once and reference out from each route? I guess that might be tough since it isn't a route in it's own right.
2. What I would find _really_ useful is if as part of my CI project build the routes diagram could be generated as an svg I could embed as part of documentation. Obviously the stats aspect would not be required. Is there an easy way to basically trigger the diagram generation from a script and write to a file. Having googled around Hawtio seems the closest thing to the diagram format I had in mind

**Comment by tadayosi** [comment]
Moved to hawtio/hawtio-next#572
