### ISSUE TITLE
The to icon is has wrong link

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-integration#19]
See the screenshot. The to icon on the left is wrong. And I fixed it in the console on the right hand side.

The wrong url is having `/java/java` 2 times as prefix instead of only 1.

![screen shot 2016-03-09 at 8 29 42 am](https://cloud.githubusercontent.com/assets/477100/13628298/5586b80e-e5d1-11e5-8c05-f96ecc4ca1f2.png)

**Comment by gashcrumb** [comment]
Ah, probably just need to change those to relative urls, will look in a few..
