### ISSUE TITLE
Camel - Source view shows a tiny panel

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-integration#2]
with the source code. We had the same problem with kubernetes, and @gashcrumb fixed this nicely. And also added a widget that used syntax highlighting. As the context in the panel would be xml, then it would be nice with syntax highlight there too.

![screen shot 2015-06-02 at 4 47 39 pm](https://cloud.githubusercontent.com/assets/477100/7938568/8c2760c4-0946-11e5-81eb-2aaf4ec8e951.png)

**Comment by gashcrumb** [comment]
It's probably due to a bunch of missing js files that are add-ons to codemirror that have to be included manually.  Have a look in hawtio-jmx's index.html you should see a big block of 'em after the bower-managed scripts.

**Comment by davsclaus** [comment]
Ah thanks @gashcrumb we embed fabric8-console, so I guess its this index.html file
https://github.com/fabric8io/fabric8-console/blob/master/index.html

And yeah it seems it miss a bunch of codemirrors that jmx has
https://github.com/hawtio/hawtio-jmx/blob/master/index.html#L81

So I guess I should just add those `ibs/codemirror/mode` javascripts to the index.html file of fabric8-console.
