### ISSUE TITLE
Camel Route Diagram: "totoal" typo

### ISSUE THREAD

**Issue by alexkieling** [hawtio/hawtio-integration#29]
Typo in Camel Route Diagram.

Steps to Reproduce:
1. Open the Web console
3. Go to Camel tab -> Route Diagram tab
4. Hover route
5. You can see typo "totoal"

Fix typo "totoal" to "total".

**Comment by astefanutti** [comment]
It's been fixed @d59a63ed04c55278c1c4839548e3faabef9909bd though it needs to be merged in 2.x branch.
