### ISSUE TITLE
Some icons for ActiveMQ plugin are not shown

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-integration#3]
See the screenshot. Its that client connector icon. It refers to a img src. Where as other icons in the tree that works are a a css class style instead.

![screen shot 2015-06-29 at 12 34 44 pm](https://cloud.githubusercontent.com/assets/477100/8406210/7ff3b658-1e5a-11e5-8622-76b54329973e.png)

**Comment by gashcrumb** [comment]
Is this inside fabric8-console?  We should check and see if those images wind up in the site build for fabric8-console if so, it should be copying all of the images under /img in the .zip file so that path still works.  At least in theory :-)

**Comment by gashcrumb** [comment]
Oh and also we should fix the link to the image so it's a relative path also, that way it'll work under any ```<base href/>``` setting.

**Comment by davsclaus** [comment]
Ah looks like the icon is not in hawtio-integration

davsclaus:~/workspace/hawtio-integration (master)/$ git grep "connector.png"
dist/hawtio-integration.js:                        node.icon = Core.url("/img/icons/activemq/connector.png");
plugins/activemq/ts/activemqPlugin.ts:            node.icon = Core.url("/img/icons/activemq/connector.png");
davsclaus:~/workspace/hawtio-integration (master)/$ find . -name 'connector.png'
davsclaus:~/workspace/hawtio-integration (master)/$

**Comment by davsclaus** [comment]
Okay @gashcrumb I found the missing AMQ icons. We had icons for Camel but non for AMQ. So I copied them over from hawtio 1.x.

So about the link fix, are you saying instead of using `/img/icons/...' it should be relative with `img/icons`

**Comment by gashcrumb** [comment]
Yeah, ideally we avoid absolute paths for sure, that way the console could be put at any context and they should still work (fingers crossed) :-)

**Comment by davsclaus** [comment]
Okay the relative path seems not working as it causes the img source to be a non valid url of the icon, see the screenshot.

![screen shot 2015-06-29 at 4 50 46 pm](https://cloud.githubusercontent.com/assets/477100/8410398/3eea1bb0-1e7e-11e5-931a-ab7e15ce5d5a.png)

**Comment by davsclaus** [comment]
Okay with absolute urls the icons works again for Camel / ActiveMQ etc.

**Comment by davsclaus** [comment]
@gashcrumb - I guess some clever stuff needs to be though to make relative urls for icons work. Or maybe some way of trapping an absolute url to the right base url and have it prepended or something?

**Comment by gashcrumb** [comment]
Yeah, but now if we put the console at say /hawtio those paths will break...

I don't understand why using the relative URL for the image wound up with that bizarre expanded path like that, we've loads of images using relative paths elsewhere that haven't had that problem.

**Comment by davsclaus** [comment]
Yeah not sure, in this example I started it locally with gulp and did a remote connect to a tomcat that has a camel app with a hawtio 1.x with jolokia included.

**Comment by gashcrumb** [comment]
Yeah, there must be some code in there that's trying to expand that image src and getting it totally wrong, will take a sec and debug it...

**Comment by gashcrumb** [comment]
Damn, it's dynatree doing it...  Well, no big deal, will add a service that returns the document base and we can build the right absolute URL then easily...

**Comment by gashcrumb** [comment]
@davsclaus Think [this commit](https://github.com/hawtio/hawtio-integration/commit/8b5588c8eb6a73dacfb4bbf47a491369487f4baf) should do the trick, requires a ```bower update```

**Comment by davsclaus** [comment]
Thanks @gashcrumb I found a few more spots in the Camel plugin to use documentBase too.

Though we have a few helper classes that do not use that module thingy, how do I get documentBase injected - Any suggestions?

See
https://github.com/hawtio/hawtio-integration/blob/master/plugins/camel/ts/camelHelpers.ts#L257-257

**Comment by gashcrumb** [comment]
Yup!   You can always get the injector via HawtioCore.injector, just check
that it's valid and then you can call get('documentBase') to get the
document Base service.

**Comment by davsclaus** [comment]
Ah like this 

https://github.com/hawtio/hawtio-kubernetes/blob/master/plugins/kubernetes/ts/kubernetesHelpers.ts#L302
