### ISSUE TITLE
master vs v2 branch

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-integration#35]
Hi @alexkieling @gashcrumb what is up with this new v2 branch? We normally use master for hawtio v2 stuff.

It seems Alex did some PRs to the v2 branch. Should we not merge them to master and then delete that v2 branch?

**Comment by gashcrumb** [comment]
@davsclaus it's a 2.0.x branch for openshift bugs.

@alexkieling you'll want to probably mrge/cherry-pick your fixes for those bugs to master as well if you haven't already, just not the `bower version patch` commits.

**Comment by alexkieling** [comment]
@davsclaus @gashcrumb Yep, I need to merge the bug fixes from v2.0.x into master. I didn't have time to do it today but will do it tomorrow.

**Comment by alexkieling** [comment]
Bug fixes merged into master.

**Comment by alexkieling** [comment]
I've got more bugs to fix on the v2.0.x branch.
