### ISSUE TITLE
Bower warning about the "main" field

### ISSUE THREAD

**Issue by alexkieling** [hawtio/hawtio-integration#37]
When installing hawtio-integration using Bower, the following message is printed:

bower hawtio-integration#~2.0.3              invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/metrics-watcher.js","dist/camelModel.js","dist/hawtio-integration.js"]

Bower expects only one main JavaScript file.

**Comment by davsclaus** [comment]
Ah okay, we can likely move metrics-watcher.jsp and camelModel.js into a sub folder. As hawtio-integration is the main file.

We would then need to adjust the path for metrics-watcher and camelModel as they are loaded from some html pages or so.
