### ISSUE TITLE
Cannot connect to remote JBoss Fuse 6.3

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-integration#39]
With the current `v1-ports` branch, trying to connect to remote JBoss Fuse 6.3 fails getting the following dialog:

![connection_failed](https://cloud.githubusercontent.com/assets/156692/21721247/d7275fb6-d46a-11e6-9170-a047ef180fba.png)

Opening the browser console, it says:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8181/hawtio/jolokia/list?canonicalNaming=false&ignoreErrors=true&_=1483714506643. (Reason: CORS header 'Access-Control-Allow-Origin' missing). (unknown)
    [workspace] Failed to load JMX tree, status:  error  error:    jqXHR:  Object { readyState: 0, getResponseHeader: .ajax/jqXHR.getResponseHeader(), getAllResponseHeaders: .ajax/jqXHR.getAllResponseHeaders(), setRequestHeader: .ajax/jqXHR.setRequestHeader(), overrideMimeType: .ajax/jqXHR.overrideMimeType(), statusCode: .ajax/jqXHR.statusCode(), abort: .ajax/jqXHR.abort(), state: .Deferred/promise.state(), always: .Deferred/promise.always(), then: .Deferred/promise.then(), 11 more… } hawtio-core.js:83:11
    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8181/hawtio/jolokia?con=fuse/&maxDepth=7&maxCollectionSize=500&ignoreErrors=true&canonicalNaming=false. (Reason: CORS header 'Access-Control-Allow-Origin' missing). (unknown)

so it seems to have something to do with CORS header.

**Comment by tadayosi** [comment]
@alexkieling @astefanutti Haven't you seen the same error?  Am I missing something regarding remote connection to Fuse?

**Comment by alexkieling** [comment]
@tadayosi I think you need to change your gulpfile.json (gulp.task('connect')) so it points to the correct port number and path. When I run Fuse, I change the values to port 8181 and targetPath 'jolokia'.

**Comment by tadayosi** [comment]
@alexkieling Changing gulp `connect` config doesn't seem to work for me. I normally use `Connect->Remote` view as it's the standard way for v1 but it also doesn't work. Worse yet, the view now seems to be broken :-(

**Comment by alexkieling** [comment]
@tadayosi Call me on IRC or BlueJeans. I'm on the hawtio channel.

**Comment by tadayosi** [comment]
I don't know why, but now just `$ gulp --port=8181` works like a charm for me. Thanks @alexkieling!

So the current remaining problem is just `Connect -> Remote` view doesn't somehow work.

**Comment by tadayosi** [comment]
Hmm, unfortunately the previous resolution was just temporary. As soon as restarting my Chrome browser, `$ gulp --port=8181` again starts to fail... The direct cause of why it previously worked but doesn't work now is the `Authorization` request header from an XHR. Somehow it was attached to the request previously but after browser restart it again starts to be omitted.

I'll look into `hawtio-jmx` further to understand what's really happening behind the scene.

**Comment by tadayosi** [comment]
OK, I've figured out what's the difference between the successful and failed paths. In my previous successful path, I accidentally tried connecting to `'/jolokia'` on a Fabric-enabled Fuse 6 instance, which turned out to work just fine. However, as soon as trying to connect to `'/hawtio/jolokia'` it starts to fail. So for a standalone Fuse 6 instance it should always fail.

Note for Fabric Fuse 6 we have two different jolokia instances, `'/hawtio/jolokia'` and `'/jolokia'` but for standalone Fuse 6 we have only one `'/hawtio/jolokia'`. Since Fabric8 v1 is already deprecated `'/hawtio/jolokia'` is always a recommended choice.

This observation coincides with @alexkieling's comment, as you said you connect to the targetPath `'jolokia'`. Probably you've tried only Fabric-enabled Fuse 6 instances and not standalone?

I'll try to figure out what really contributes to this difference between `'/hawtio/jolokia'` and `'/jolokia'` on Fuse 6.

**Comment by alexkieling** [comment]
I usually run `./dev/jboss-fuse-6.3.0.redhat-187/bin/fuse` and connect to
`/jolokia`. That's just a way that has worked well for me. First time I
open the Web console, it shows a dialog box asking for authentication. I
just enter admin/admin. I've never connected to `/hawtio/jolokia` but will
do if it's the recommended approach. Let us know how to do it.

There is also the strategy that Antonin follows. It could be an easy one.
How do you do it, again?

**Comment by astefanutti** [comment]
For non OSGi stuff, I run `mvn hawtio:*` inside a sample project. See http://hawt.io/maven/.

**Comment by tadayosi** [comment]
Thanks all!  I fixed it at hawtio/hawtio-node-backend#4.
