### ISSUE TITLE
Camel plugin - Make it easier to show all routes in routes diagram

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-integration#4]
So when you click "routes" in the tree we should have a diagram button so you can see all of these routes on the same page.

And as bonus we should maybe have some filter box where you can filter by routes, and/or some selector to include/exclude by route id. Maybe some slider that you can slide in / out to do this.

**Comment by davsclaus** [comment]
yay so you got the button now on the routes folder to show them all. But the layout is a bit to dense / clever ;)

![screen shot 2015-06-30 at 3 55 10 pm](https://cloud.githubusercontent.com/assets/477100/8432313/9e314e9c-1f3f-11e5-88a7-5b0d054801a8.png)

There are 2 routes, and the 1st is just from -> to. And the 2nd is that from -> choice that is bigger.

**Comment by davsclaus** [comment]
We need to port the v1 -> v2 select routes dialog

**Comment by akieling** [comment]
@davsclaus could you please pull the latest code and confirm your open issues are still required?
