### ISSUE TITLE
Description element should not generate a new box

### ISSUE THREAD

**Issue by johan-carlsson** [hawtio/hawtio-integration#41]
Hi 
It would be great if the Route Diagram did not display the <description> element as separate box.

Example: 
<setProperty propertyName="name" id="setName">
  <description>A description</description>
  <jsonpath>$.name</jsonpath>
</setProperty>

The above generates a separate box for the description element.

Ideally the description should be shown when hovering over the setProperty box. But even just filter out the description boxes would be an improvement.

Kind regards
/Johan

**Comment by akieling** [comment]
@astefanutti 
Do you think we should filter the Description nodes in `routeDiagram.ts` or in `camelHelpers.ts`?
https://github.com/hawtio/hawtio-integration/blob/e1680fdf82f9be3cdcf91bea4f8e7c1e383bf05d/plugins/camel/ts/routeDiagram.ts#L95-L96
https://github.com/hawtio/hawtio-integration/blob/e1680fdf82f9be3cdcf91bea4f8e7c1e383bf05d/plugins/camel/ts/camelHelpers.ts#L1011

**Comment by KarlAbert** [comment]
+1
