### ISSUE TITLE
error TS2339: Property 'findIndex' does not exist on type 'NodeSelection[]'

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-integration#44]
I've just declared more types and it revealed seemingly ES5 incompatibility issues:
```
plugins/activemq/ts/activemqPlugin.ts(128,41): error TS2339: Property 'findIndex' does not exist on type 'NodeSelection[]'.
plugins/camel/ts/breadcrumbBar.ts(118,56): error TS2339: Property 'find' does not exist on type 'NodeSelection[]'.
plugins/camel/ts/breadcrumbBar.ts(148,54): error TS2339: Property 'find' does not exist on type 'NodeSelection[]'.
```

I think it's just the tip of the iceberg, as there are many places where types are not declared but `any` is used so the incompatibility issues are buried.

@alexkieling @astefanutti What do you think would be the right approach to fix it?  Introducing `es6-shim`?  Upgrading the target to `ES6`?

**Comment by astefanutti** [comment]
ES6 is definitely the long term solution. That being said, I'm not sure whether we want to drop older browsers support (that may have already been happening already with Flexbox use for example).

In the short term, I'd rather avoid introducing yet another solution and would rely on Lodash.

That doesn't alleviate the need to strengthen our type definitions. I don't think it's that bad in the current state for the ES6 issue as we have been fixing quite a lot of them already.

I've fixed it @800a307  using Lodash to fix compilation but let's discuss the next steps if any.

**Comment by tadayosi** [comment]
@astefanutti Ah, thanks. 800a307902d982c342aad01b318fdb821c7c6e96 looks great. I agree that we rely on Lodash for older browsers support.

**Comment by astefanutti** [comment]
@tadayosi ok sounds good. Let me close this then.

**Comment by nirvanacanadagit** [comment]
ok sounds good. Let me close this then.
