### ISSUE TITLE
Camel tab tree view does not list all camel contexts

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-integration#45]
I've been playing with 2.0-M2 on WildFly / EAP and noticed an issue with the Camel context tree.

The tree view only seems to display one Camel context. If I deploy 2 camel applications into the container, I only ever see one of them. 

In addition, the displayed Camel context changes depending on the name of the context. E.g it's picking the first one based on ascending order of context names.

**Comment by astefanutti** [comment]
Thanks a lot for the report.
