### ISSUE TITLE
Deleting all camel contexts leaves camel tab in unclean state

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-integration#46]
If you delete all available Camel contexts, the view you're left with is a bit messy....

The Camel tab link is removed from the sidebar (as there's no active Camel apps anymore), but the context tree is still visible (but somewhat broken) showing the remnants of the last deleted context.

**Comment by alexkieling** [comment]
Can you test again? I think it's fixed.

**Comment by jamesnetherton** [comment]
Yes, I forgot to close this one.

It was fixed in https://github.com/hawtio/hawtio-integration/commit/c3bd251ca7c1e4bae4ce89e192f7225f260b69cc.
