### ISSUE TITLE
Camel tracer - The slider does not work to show the traced or debugged message

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-integration#5]
eg clicking on the blue message id should show a slider with message details. This also does not work for the debugger.

![screen shot 2015-06-30 at 6 00 45 pm](https://cloud.githubusercontent.com/assets/477100/8435365/25f4708c-1f51-11e5-803c-da78229d7b1d.png)

**Comment by davsclaus** [comment]
Okay so the browse endpoints is the only working due it reuses some code from ActiveMQ plugin. The code in Camel plugin dont work with the slider.

**Comment by davsclaus** [comment]
Okay for some odd reason then after the dialog has been show and closed once, then it does not show on 2nd click. The navigation works fine in the dialog.

**Comment by davsclaus** [comment]
Okay got it working on the tracer tab. But for debug there is still a little problem left.

**Comment by davsclaus** [comment]
I think the debugger should be a bit reworked as you only show 1 message, eg the suspended message. So we could make the slider always on, and take up 25% of the lower screen etc.

**Comment by gashcrumb** [comment]
Maybe it'd make more sense not to have the slider and just have an area where the message is visible?

**Comment by gashcrumb** [comment]
The idea is sometimes it's nice to see how the message changes between steps, right?

**Comment by davsclaus** [comment]
Yeah you can use the up down buttons to move next/prev and the diagram changes and highlights the node. Though for tracer you can accomulate many messages as it remembers old messages. Where as the debugger is only about the current message.

**Comment by davsclaus** [comment]
The slider is always enabled for the debugger as we only show one message.
