### ISSUE TITLE
Camel tree disappears when reloaded

### ISSUE THREAD

**Issue by akieling** [hawtio/hawtio-integration#50]
The Camel tree disappears when reloaded.
The tree is reloaded on some user actions, such as deleting a route or pressing F5 to reload the page.
Note: the JMX tree doesn't have this issue.
@astefanutti

**Comment by akieling** [comment]
@astefanutti Please have a look at this issue when possible.

**Comment by astefanutti** [comment]
I can reproduce. It seems a bit more general than the tree, e.g. the routes tab is still loading, but that may be a side effect of the tree loading issue.

**Comment by astefanutti** [comment]
Note that navigate back to the Camel tab makes the tree appearing. So probably just a digest thing...
