### ISSUE TITLE
Camel - Cannot show message headers

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio-integration#6]
In the browse endpoint and trace and debug functions then the headers are not shown. There is a expander to show them, but the headerHtml is not shown, despite the source code builds a <tr> structure with the data.

**Comment by davsclaus** [comment]
![screen shot 2015-07-01 at 5 14 53 pm](https://cloud.githubusercontent.com/assets/477100/8457801/d6e9c8ca-2013-11e5-86a5-43e742ccf12e.png)

**Comment by davsclaus** [comment]
Notice the headers is empty. But ```              <tbody ng-bind-html="row.headerHtml">``` contains the html structure with 3 headers.

**Comment by gashcrumb** [comment]
Wonder if doing ```<tbody compile="row.headerHtml"></tbody>``` would work better...

**Comment by davsclaus** [comment]
Yay works now. Thanks.
