### ISSUE TITLE
Spring Boot - health component doesnt render CompositeHealthIndicator checks well 

### ISSUE THREAD

**Issue by macgregor** [hawtio/hawtio-integration#61]
![screen shot 2018-10-01 at 3 09 37 pm](https://user-images.githubusercontent.com/2407678/46310030-2e703900-c58c-11e8-94f1-625db5e61749.png)

Spring Boot Version: 1.5.14.RELEASE
Hawtio Version: 2.0.3

org.springframework.boot:type=Endpoint,name=healthEndpoint, Data:
```
{
  "activemq": {
    "openwire": {
      "status": "UP"
    },
    "amqp": {
      "error": "javax.jms.JMSException: Transport connection remotely closed.",
      "status": "DOWN"
    },
    "stomp": {
      "status": "UP"
    },
    "status": "DOWN"
  },
  "diskSpace": {
    "total": 500068036608,
    "threshold": 10485760,
    "free": 315355197440,
    "status": "UP"
  },
  "ldapHealthcheck": {
    "vendor": "Ping Identity Corporation",
    "version": "UnboundID LDAP SDK for Java 4.0.8",
    "status": "UP"
  },
  "db": {
    "activemqLockerDataSource": {
      "database": "H2",
      "hello": 1,
      "status": "UP"
    },
    "activemqPersistenceDataSource": {
      "database": "H2",
      "hello": 1,
      "status": "UP"
    },
    "status": "UP"
  },
  "status": "DOWN"
}
```

The activemq check is my own (the standard JMS health indicator looks similar), but the [db](https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/DataSourceHealthIndicator.java) is a standard actuator health check. Looking briefly, it seems like [health.ts](https://github.com/hawtio/hawtio-integration/blob/master/plugins/spring-boot/health/health.ts) and/or [health.service.ts](https://github.com/hawtio/hawtio-integration/blob/master/plugins/spring-boot/health/health.service.ts) needs to be a little more sophisticated with its to string conversion. 

Seems like a good candidate for someone wanting a simple improvement to work on, which unfortunately isnt me right now :)

**Comment by alexkieling** [comment]
It looks like the Card View isn't the best view for hierarchical data. We could try replacing it with headings and lists.
