### ISSUE TITLE
Camel REST Services tab is never activated

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-integration#63]
There's a feature for displaying routes configured using the Camel REST DSL. 

If you select the a camel context or the 'routes' folder from the tree, there should be a 'REST Services' tab if the Camel Context makes use of the REST DSL.

This may not have ever worked in V2. It's definitely not worked in any Fuse 7 release. Would could debate whether we want to keep the feature or not. Screenshot below of what it looks like.

![rest-services](https://user-images.githubusercontent.com/4721408/47076368-74690600-d1f6-11e8-92ac-9e00cd7675f1.png)

**Comment by alexkieling** [comment]
It should show up in v2. I'll have a look.
