### ISSUE TITLE
Spring Boot Health component does not cancel Jolokia polling

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-integration#66]
Seems that exiting the Spring Boot health screen fails to cancel the timer which polls Jolokia in order to refresh the health stats.

If you navigate away from the health page and then watch the network requests, you'll see Jolokia requests for:

```
{"mbean":"org.springframework.boot:type=Endpoint,name=Health","type":"exec","operation":"health"}
``` 

It gets incrementally worse each time you visit and browse away from the Spring Boot health page.

**Comment by alexkieling** [comment]
@jamesnetherton please test it
