### ISSUE TITLE
Incorrect handling of AMQ queue name with * character

### ISSUE THREAD

**Issue by christian-morin** [hawtio/hawtio-integration#70]
When trying to move a message to a queue in ActiveMQ, the dropdown doesn't handle queue-names with *-characters correctly (instead `&ast;`). This is quite common in our AMQ-queues related to topics. And when trying to move the message to the queue, the message is simply dropped instead of moved (even if it says it moved it).

The queue in the screenshot is actually named TMP.QUEUE.*

![Screenshot 2019-04-04 at 11 29 09](https://user-images.githubusercontent.com/14925434/55545173-f11c6d80-56cc-11e9-8aeb-1a5e04ee4c3f.png)

![Screenshot 2019-04-04 at 11 36 27](https://user-images.githubusercontent.com/14925434/55545663-f62dec80-56cd-11e9-82ae-a43f17bc41f6.png)

```
Failed to register MBean org.apache.activemq:type=Broker,brokerName=AMQ001T1,destinationType=Queue,destinationName=TMP.QUEUE.&ast; | org.apache.activemq.broker.jmx.ManagedRegionBroker | qtp1793417016-20
```

Queue names look correct everywhere else.

Hawtio 2.5.0 (Servlet container)
ActiveMQ 5.15.8

**Comment by alexkieling** [comment]
Fixed only the move action. If you find other bugs, please create new issues.
https://github.com/hawtio/hawtio-integration/commit/33488f4ccbceac79d62f71c458eca6058ccfc9b6
