### ISSUE TITLE
ActiveMQ plugin - strange contents of treeview

### ISSUE THREAD

**Issue by bligny** [hawtio/hawtio-integration#75]
I'm running hawtio 2.7.0 under Wildfly 17.
(NB: I changed the jmx domain of Wildlfy Artemis so that ActiveMQ plugin can kick-off)

The displayed treeview for ActiveMQ is a bit strange  (see screenshot): 
- it is "as if" the JMX mbeans were splitted into 2 separate but identical "addresses" tree nodes
- some JMS queues are displayed with a folder icon, others with a box icon (although being regular queues like the first ones)

I verified the exposed mbeans  with JConsole: they are not like displayed in Hawtio.
Any idea ?

**Hawtio**
![image](https://user-images.githubusercontent.com/19853549/60868050-6d729f80-a22c-11e9-9d5f-0491915ba800.png)

**JConsole**
![image](https://user-images.githubusercontent.com/19853549/60870087-736a7f80-a230-11e9-83be-ca59bf946b46.png)

**Comment by jamesnetherton** [comment]
The ActiveMQ plugin has only been proven against ActiveMQ 5.x. So the extent to which it works with Artemis has not been verified.

**Comment by bligny** [comment]
Is it imaginable that this plugin will be one day or another verified to also work with Artemis ?

IMHO, it's pretty easy to **test** (I did not say easy to **fix**):
1. Download and install Wildfly 17
2. Edit the file standalone/configuration/standalone-full.xml 
- enable JMX
- change Artemis domain name to "org.apache.activemq"
```xml
<subsystem xmlns="urn:jboss:domain:messaging-activemq:7.0">
            <server name="default">
                <management jmx-enabled="true" jmx-domain="org.apache.activemq"/>
```
3. Drop "hawtio-wildfly-2.7.0.war" into standalone/deployments
4. Start Wildfly (using the full config - the one with JMS):
```bash
./standalone.sh --server-config=standalone-full.xml 
```

**Comment by alexkieling** [comment]
Try contacting the Artemis team and asking what they plan to offer regarding Web management.

**Comment by bligny** [comment]
As stated on their website (https://activemq.apache.org/), Artemis is the next major version of ActiveMQ

> Once Artemis reaches a sufficient level of feature parity with the 5.x code-base it will become ActiveMQ 6.

**So sooner or later, Artemis will replace ActiveMQ, and Hawtio ActiveMQ plugin will need to be updated**. Therefore, I find legitimate to ask whether Hawtio team plans to do such update.

Keep also in mind that there is a HUGE community of Redhat Wildfly users who would be glad to use Hawtio to monitor their app server (including its embedded Artemis JMS broker).

**Comment by tadayosi** [comment]
Note Artemis already has developed and includes its own plugin as the embedded management console, which is still based on Hawtio 1.x.
https://activemq.apache.org/components/artemis/documentation/latest/management-console.html
This is fully compliant with the latest Artemis version, so if you are interested in the management UI check the embedded console which Artemis standalone provides.

So currently Artemis team owns the codebase and to avoid duplicate efforts we've decided not to upgrade the plugin by ourselves at this moment. I believe Artemis team is looking to upgrade their plugin to Hawtio 2.x so hopefully it will be available in the near future.

The current ActiveMQ plugin included in Hawtio 2.x is provided solely for the legacy ActiveMQ users and is not intended to keep up-to-date with the latest Artemis development.

**Comment by alexkieling** [comment]
@bligny have you found an alternative Web console to manage Apache Artemis?

**Comment by bligny** [comment]
@alexkieling not really. We finally decide to stick to Hawtio 1.x, surely less sexy than Hawtio 2, but yet meets our basic requirement: have a **single** console to monitor our application server (including JMS queues).
Concretely speaking, our config is:
- Wildfly 17.0.1
- Hawtio 1.5.11
- artemis-plugin-2.8.1
