### ISSUE TITLE
Problem with drawing a diagram when using a split node

### ISSUE THREAD

**Issue by Piotrek199612** [hawtio/hawtio-integration#76]
I'm running hawtio 2.7.0
The given source produces such a diagram. I think all paths should connect to the "to" node. 
Am i correct?
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<routes xmlns="http://camel.apache.org/schema/spring">
    <route customId="false" id="route1">
        <from uri="direct:start"/>
        <split id="split1">
            <expressionDefinition>tokenize(simple{${body}},)</expressionDefinition>
            <choice id="choice1">
                <when id="when1">
                    <expressionDefinition>simple{${body}} contains When 2</expressionDefinition>
                    <log id="log1" message="When 2"/>
                </when>
                <when id="when2">
                    <expressionDefinition>simple{${body}} contains When 3</expressionDefinition>
                    <log id="log2" message="When 3"/>
                </when>
                <otherwise id="otherwise1">
                    <log id="log3" message="When 4"/>
                </otherwise>
            </choice>
        </split>
        <to id="to1" uri="direct:end"/>
    </route>
</routes>
```

![RouteDiagram](https://user-images.githubusercontent.com/26096156/61071169-b08d6800-a410-11e9-9a21-885326ce3b08.png)

When I remove split node then it looks ok.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<routes xmlns="http://camel.apache.org/schema/spring">
    <route customId="false" id="route1">
        <from uri="direct:start"/>
        <choice id="choice1">
            <when id="when1">
                <expressionDefinition>simple{${body}} contains When 2</expressionDefinition>
                <log id="log1" message="When 2"/>
            </when>
            <when id="when2">
                <expressionDefinition>simple{${body}} contains When 3</expressionDefinition>
                <log id="log2" message="When 3"/>
            </when>
            <otherwise id="otherwise1">
                <log id="log3" message="When 4"/>
            </otherwise>
        </choice>
        <to id="to1" uri="direct:end"/>
    </route>
</routes>
```
![obraz](https://user-images.githubusercontent.com/26096156/61071629-e54def00-a411-11e9-93bc-3e2a6e128ae2.png)

**Comment by Piotrek199612** [comment]
https://github.com/hawtio/hawtio-integration/blob/e1680fdf82f9be3cdcf91bea4f8e7c1e383bf05d/plugins/camel/ts/camelHelpers.ts#L1109
When I change this line to:
`if (parenNodeName === "choice" || nodeId === "split") {`
 then it looks ok but i don't know if it won't break down something else.

![obraz](https://user-images.githubusercontent.com/26096156/61146163-a5ead580-a4d9-11e9-8544-cb1eb5965a87.png)

**Comment by astefanutti** [comment]
@Piotrek199612 thanks for the analysis.

For reference, the initial change is hawtio/hawtio@9593bbc022ca611369816e36a6caeabdd267fef4. I'm not sure I remember all of it, though at first glance I would have tried to touch:

https://github.com/hawtio/hawtio-integration/blob/e1680fdf82f9be3cdcf91bea4f8e7c1e383bf05d/plugins/camel/ts/camelHelpers.ts#L1112

And add your change there: `|| nodeId === "split"`.

Ideally, it should handle other _fan-in_ tags but it'd be great if you could create a PR for `split`.

**Comment by Piotrek199612** [comment]
@astefanutti 
Yes you are right, it works when I add the change to this line. 
https://github.com/hawtio/hawtio-integration/blob/e1680fdf82f9be3cdcf91bea4f8e7c1e383bf05d/plugins/camel/ts/camelHelpers.ts#L1112
This problem also affects:
- aggregate
- choice
- delay
- filter
- loadBalance
- loop
- multicast
- resequence
- sample
- split
- throttle
Are there any other tags that I missed and should be corrected?

**Comment by astefanutti** [comment]
I'm not sure whether the `delay`, `sample` and `throttle` can actually have nested outputs?

I wonder as well about `doTry`/`doFinally`, `idempotentConsumer` and `interceptFrom` and `onCompletion`. These are more advanced EIP, so your initial list would be a great improvement anyway over the existing, limited, one.

It'd be great to have a sample test file, that could be use to verify the rendering, at least manually. I remember I started to assemble one when I worked on the diagramming, but it seems I didn't commit it.

**Comment by Piotrek199612** [comment]
I have wrongly finished `delay` with the `end` instruction.
<pre>
from("direct:start")
   <b> .delay(100)</b>
        .choice()
            .when(body().contains("When 2"))
                .log("When 2")
            .endChoice()
            .when(body().contains("When 3"))
                .log("When 3")
            .endChoice()
            .otherwise()
                .log("When 4")
            .endChoice()
        .end()
   <b> .end()</b>
.to("direct:end");
</pre>
So then, such an xml was generated
```
<route xmlns="http://camel.apache.org/schema/spring" id="route1">
        <from uri="direct:start"/>
        <delay>
            <expressionDefinition>100</expressionDefinition>
            <choice>
                <when>
                    <expressionDefinition>simple{${body}} contains When 2</expressionDefinition>
                    <log message="When 2"/>
                </when>
                <otherwise>
                    <log message="When 4"/>
                </otherwise>
            </choice>
        </delay>
        <to uri="direct:end"/>
    </route>
```
I made the same mistake with `sample` and `throttle` instructions.
So now I will prepare PR for commands I wrote before without `delay`, `sample` and `throttle`.
Should I change this condition 
https://github.com/hawtio/hawtio-integration/blob/e1680fdf82f9be3cdcf91bea4f8e7c1e383bf05d/plugins/camel/ts/camelHelpers.ts#L1112
to ```else if (nodeId === "choice" || nodeId === "aggregate" || nodeId ==="filter " ... )``` or there is any smarter solution?

**Comment by astefanutti** [comment]
I still cannot figure out a generic solution for it. We can go for the hard-coded list and comment that it may be possible to improve it.

I was thinking `pipeline` should be added too. That being said, it may be just equivalent as pipeline is supposed to have a single output if I'm not mistaken...
