### ISSUE TITLE
Camel traces table height increases and shrinks route diagram

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio-integration#98]
As more traces are added to the traces table, its height increases and the Camel route diagram shrinks until it is no longer visible.

**Comment by Skrrytch** [comment]
This is not yet solved.

Another nice feature would be a pop-up window with the diagrams... to have more space for data while looking at the diagrams in maximum size :-)

I'd like to contribute but I am not sure how to start and test modifications locally with hast.io application . It's there any description?

Documentation for developers on hawt.io webpage results in 404...
